### PR TITLE
A patch to solve issue #106

### PR DESCRIPTION
**Pull request by xueliangliang**
I reduced the `tracerStateFieldCount` to 2 to make it compatible with Pivotal Cloud Foundry's tracing implementation.

### CODE REVIEW

**Comment by xueliangliang** [comment]
Any concern to block this PR?

**Comment by basvanbeek** [comment]
Can you add a unit test which lets this package consume a span context that would have failed without this PR?

**Comment by xueliangliang** [comment]
@basvanbeek I added two special environment variables to simulate that only `X-B3-SpanID` and `X-B3-TraceID` available. If the `tracerStateFieldCount` is 3, it will cause error.

Please help review and verify. Thanks.

**Comment by basvanbeek** [comment]
Closing due to age. This solution does not properly fix the broken B3 handling issue and adds undesired configuration logic through environment variables. Maybe #119 will be updated to be inline with B3 specs.

**Pull request closed without merging**
